### ISSUE TITLE
Horizontal Scroll option.

### ISSUE THREAD

**Issue by kmvenkatesh** [VolkovLabs/business-table#102]
It seems there is no horizontal scroll bar in business table. Is it possible to add?

**Comment by mikhail-vl** [comment]
@kmvenkatesh You need to set `min width` for Auto Width or just a `width` for columns to show a horizontal scroll bar.

![Screenshot 2024-10-05 at 6 20 31 PM](https://github.com/user-attachments/assets/88f7058a-a8cd-489c-bb0d-ff41c2d524b9)
