### ISSUE TITLE
Request For New Feature in Editable Data

### ISSUE THREAD

**Issue by KaungMAung** [VolkovLabs/business-table#103]
First of all, Thank you so much for this wonderful plugin.

For Editable Data, Right now we have 4 types (String, Number, Select and DateTime). I would like to request for one more type which is Text Box. Right now, we can use String to enter the data, but couldn't see for longer text when entering data. Textbox type will help a lot.

Thanks and Rgds,
K

**Comment by mikhail-vl** [comment]
@KaungMAung Thank you for the feature request. We will add in the upcoming release.

**Comment by KaungMAung** [comment]
When adding Text Box, Please check or help to handle, New Line Character (When user key in Enter for next line). Because this issue happened in Text Area type of Business Form version 4.7 as well (https://github.com/VolkovLabs/business-forms/issues/516 )

Thanks and Rgds,
K

**Comment by mikhail-vl** [comment]
@KaungMAung Thank you to bring it to our attention. We are investigating.
