### ISSUE TITLE
Nested Objects feature documentation

### ISSUE THREAD

**Issue by AbelThorne** [VolkovLabs/business-table#115]
Hello and thanks for the high quality Grafana plugins you're providing.

I've downloaded Business Table latest version but I can't find anywhere documentation or tutorials on how to use Nested Objects. Not even how the look and feel of feature is supposed to look. Looking into the relevant PR, I can find an example dashboard but nothing I've tried to adapt the queries work. I'm trying to use it with a BigQuery datasource so maybe the problem comes from there. Any pointers to documentation or help would be welcome.

Thanks in advance

**Comment by mikhail-vl** [comment]
@AbelThorne Thank you for following our latest releases.

  We just finished a release blog with details: https://volkovlabs.io/blog/business-table-1.5.0/
  @daria-vl will update documentation later today and she is working on a YouTube tutorial for Editable data and Nested objects targeted for next week.

  Nested objects is experimental feature and we are looking forward for the feedback from the community.
