### ISSUE TITLE
feature request: dynamic url

### ISSUE THREAD

**Issue by yosiasz** [VolkovLabs/business-table#116]
greetings!

Amazing high quality work as always! Congrats on new plugin. in good old BT we can do this for dynamic url

```
<div>
<table>
<th>Failed Calls</th>
<th>Match False</th>
<th>Retries</th>
<th>Failure Rate</th>
<th>Failure %</th>
{{#each data}}
<tr>  
  <td>{{ 'Failed Calls' }}</td>
  <td>{{ 'Match False' }}</td>
  <td>{{ 'Retries' }}</td>
  <td>{{ 'Failure Rate' }}</td>
  <td><a href= {{ url }} >{{ 'Failure %' }}</a></td>
</tr>  
{{/each}}

<table>
</div>
```

Would be a nice feature in this new plugin.

![image](https://github.com/user-attachments/assets/1311b15f-7571-44c1-a820-4951975e6ac2)

Thanks!

**Comment by mikhail-vl** [comment]
@yosiasz The right way is to use data links override which are supported already in the panel.

  We won't support HTML or JS in the Business Table to make it Enterprise friendly.
