### ISSUE TITLE
Data link on group table value

### ISSUE THREAD

**Issue by Nesweikas** [VolkovLabs/business-table#122]
Hi is it possible to put data link on grouped raw as in this example on "platform" and "service" fields ? then i don't use grouping i can put on any field datalink, but not for grouped values.
![image](https://github.com/user-attachments/assets/1b49babb-8263-4744-a208-0e1ee74f9bc0)

**Comment by mikhail-vl** [comment]
@Nesweikas Group rows are synthetic values and they don't support data links.

 It's not possible to fully implement data links on group values and we won't do it to avoid confusion from other users.
