### ISSUE TITLE
Sort setting resets

### ISSUE THREAD

**Issue by caldiver07** [VolkovLabs/business-table#127]
When the panel refreshed the sort setting is lost and defaults back to original.

**Comment by mikhail-vl** [comment]
@caldiver07 That's correct. We don't save updated sort settings in the panel options like native Table panel.

  It's the 2nd time I hear about it and we will discuss it internally to support it in future versions.

**Comment by caldiver07** [comment]
interesting. but you do save the filter settings but not the sort settings?  A bit inconsistent?
