### ISSUE TITLE
Filter options are like and not = 

### ISSUE THREAD

**Issue by caldiver07** [VolkovLabs/business-table#128]
the filter options are filter as a "like" and not as an '="

**Comment by mikhail-vl** [comment]
@caldiver07 Thank you for bringing it to our attentions. We will look into it.

**Comment by caldiver07** [comment]
any update on this...

**Comment by mikhail-vl** [comment]
@caldiver07 We are looking at opened issues one by one and recently started working on the upcoming release.

  If it's a Production issue and needs to be checked on priority please join Business Suite Enterprise: https://volkovlabs.io/pricing/
