### ISSUE TITLE
Business table - sometimes the rows disappear

### ISSUE THREAD

**Issue by davecarcu** [VolkovLabs/business-table#132]
I populated table with 8 queries , and sometimes a row disappears and reappears.
I can't undertstan because query are identical ( only the address chenges).
Individually query are working but not propely displayed in table.

**Comment by davecarcu** [comment]
![Grafa1](https://github.com/user-attachments/assets/2a85702f-8a32-48c5-b1a6-1dfc02e8dd03)
Here the table configuration , as you can see query are 8 and rows in table are 7

**Comment by davecarcu** [comment]
![Query_ins](https://github.com/user-attachments/assets/2e07d61e-a39a-4027-bddb-7da6cb42634e)
![Query_ins2](https://github.com/user-attachments/assets/af64acbe-dfad-4b4c-8ddf-cbc43e7e2e75)
Here query inspect
As you can see row sometimes are not equal to query
How can i fix it ?

Thank you

**Comment by mikhail-vl** [comment]
@davecarcu This issue is not related to the Business Table panel. It's a data issue.

  If your data source (Infinity) does not return all rows, it's probably an API rate limiting issue.
  If it's internal API, check with the API team. If 3rd party check the limit for number of concurrent requests.
