### ISSUE TITLE
POPUP or CheckBox table editing

### ISSUE THREAD

**Issue by Juarezarq** [VolkovLabs/business-table#144]
<img width="1003" alt="Captura de pantalla 2024-10-29 a las 13 45 37" src="https://github.com/user-attachments/assets/d4383de3-127a-48e1-9151-5d39fa1dafd9">

Hi!,
I am trying with Business Table plugin....
How to create an independent value list, for the popup menu shown on the imagen, in order to edit row by row.

Even more convenient for me: How to make a check box row by row, to choose between true and false?

Thanks!!

**Comment by mikhail-vl** [comment]
@Juarezarq Please watch YouTube video to learn how to configure editable Select field: https://www.youtube.com/watch?v=wiy6bBJDdb0

  Business Table does not provide editable checkbox element, we can look into adding it.

**Comment by Juarezarq** [comment]
Thank you for your answer Mikhail,

On the query B, I get two values: true and false. The should appear on the dropdown menu, but I can’t see any one. 

If I convert the edition type to string, and I try to change the field to true, I get the error:  {"refld":"A", "message": "invalid measurement" "status":500}. The change does not take place. 


Thank you in advance!!

￼￼
￼


Saludos,

Juan Regojo Zapata
Jefe de Proyectos
Tel: 687792819
***@***.*** 

ADVERTENCIA LEGAL PARA ENVÍOS COMERCIALES PERSONALIZADOS POR CORREO ORDINARIO Y/O ELECTRÓNICOS

 Sus datos personales han sido obtenidos con su consentimiento y forman parte de un fichero automatizado cuyo responsable es Juan Regojo Zapata, con Domicio en Calle Madre Amor de Dios 9 11500, del Puerto de Santa María, Cádiz,  donde puede ejercitar sus derechos de acceso, rectificación, cancelación y oposición.
Este mensaje va dirigido exclusivamente a la persona designada como destinatario y la información que contiene es confidencial. Si Vd. ha recibido este mensaje por error le rogamos nos lo comunique mediante correo electrónico remitido a nuestra atención y proceda a su eliminación así como a la de cualquier documento adjunto al mismo, quedando prohibida cualquier divulgación, distribución o copia del mismo. 
La recogida y tratamiento de los datos se realizará de acuerdo con la Ley Orgánica 7/2021, de 26 de mayo, de Protección de Datos Personales y garantía de los derechos digitales.
