### ISSUE TITLE
Group collapse on refresh

### ISSUE THREAD

**Issue by hoffmanroni** [VolkovLabs/business-table#145]
I'm just trying this panel out now and I see that if I have a grouped row with auto refresh on, the table auto collapses all the rows on each refresh.  Its not really usable with higher frequency refresh since its always collapsing the rows each time.

![image](https://github.com/user-attachments/assets/5b2edafe-b9aa-44d7-9d10-da2924b2946b)

**Comment by mikhail-vl** [comment]
@hoffmanroni Thank you for submitting a future request. We will look into adding state persistence for opened groups.

**Comment by boozelclark** [comment]
Having a default state for opened groups would be great too. Being able to load with the groups expanded would be extremely useful.

**Comment by mikhail-vl** [comment]
@boozelclark Already planned in https://github.com/VolkovLabs/business-table/issues/121

**Comment by hoffmanroni** [comment]
@mikhail-vl also fyi the sorting is getting reset as well.

**Comment by mikhail-vl** [comment]
@hoffmanroni Planned in https://github.com/VolkovLabs/business-table/issues/127
