### ISSUE TITLE
BUG : error when editing a string field in text area mode

### ISSUE THREAD

**Issue by Bruutal** [VolkovLabs/business-table#170]
Datasource type : PostreSQL database
query exemple : select null as string_field

Layout config : 
![layout](https://github.com/user-attachments/assets/00381244-544c-4f3e-b5ec-8be4e75d3fd0)

Edit config :
![edit](https://github.com/user-attachments/assets/6070aff7-3ebd-4b25-9216-5c0237cc1f71)

Error : 
![error](https://github.com/user-attachments/assets/c2bd8e34-9550-42ff-b2ca-d5ef6ef4f9fa)

When I click edit on a row containing an editable string field and the current string value is null, I get the error "Cannot read properties of null (reading 'replaceAll')". The error appears whether there is an update request or not.

**Comment by vitPinchuk** [comment]
@Bruutal Thank you for the open issue

What data type is contained in the field you use for `string_field`
Can you please provide more details using “table view” mode (screenshot) ?
![image](https://github.com/user-attachments/assets/4ecd00ea-392e-479c-8fed-1e10ce0a6f9e)

Thank you

**Comment by KaungMAung** [comment]
For this issue, remedy before update is that use your query to assign "" or " " if value is NULL. I think it would work. @Bruutal
