### ISSUE TITLE
Business Table version version 1.6.0, Text Area error for \n (next line character)

### ISSUE THREAD

**Issue by KaungMAung** [VolkovLabs/business-table#173]
Grafana Version 11.2.2
Business Table version version 1.6.0
Issue:
Once enter nexxt line (CR) character at Text Area and submit.It can successfully submitted and update data in DB.
But when edit again, and submit, got error "Error: Bad control character in string literal in JSON at position 143 (line 5 column 77)"
If we remove next line character, we can submit. This can be reproduced.

Thanks and Rgds,
K
![image](https://github.com/user-attachments/assets/d48418f2-fae7-4eec-9714-4079e6d74e5c)

**Comment by KaungMAung** [comment]
I found out that Business Table version version 1.7.0 also behave same way. You need to at least do some edit to Text Area Field (like just space and delete back), then we can submit. If not, it will show error.

**Comment by mikhail-vl** [comment]
@KaungMAung The issue supposed to be updated in v1.7.0.

  @vitPinchuk Could you please double check "You need to at least do some edit to Text Area Field (like just space and delete back), then we can submit. If not, it will show error.".

**Comment by KaungMAung** [comment]
I did try with 1.7.0 and encountered same issue.

**Comment by mikhail-vl** [comment]
@KaungMAung We will double check and update in the upcoming v1.8.0.

**Comment by KaungMAung** [comment]
@mikhail-vl  thank you so much. I will raise feature request separately for displaying Text in Text Area. Right now, it displays like a string without newlines.

**Comment by mikhail-vl** [comment]
@KaungMAung Please do.
