### ISSUE TITLE
Business Table Pagination feature request

### ISSUE THREAD

**Issue by KaungMAung** [VolkovLabs/business-table#178]
For Business Table Pagination, feature to pre-set number of item displayed to default will be great.
Currently default is always 10 and can select to 10,20,50,100,1000. 
If we can set default like let's say 20. That will be really nice.

Thanks and Rgds,
K

**Comment by mikhail-vl** [comment]
@KaungMAung Thank you for opening feature request. Should be easy to implement in the upcoming release.

**Comment by KaungMAung** [comment]
@mikhail-vl  @vitPinchuk Thank you so much. Ver 1.8 really solved the issue in new line case. I have tested and working well. Looking forward to 1.9. You guys are really great.
