### ISSUE TITLE
capture row click to get value to use on another table

### ISSUE THREAD

**Issue by yosiasz** [VolkovLabs/business-table#196]
Greetings,

Again another amazing plugin! Is there a click even on rows I can capture to use one of the columns' value I can then turn around and use for another query?

In this case I want to capture Category Code value

![image](https://github.com/user-attachments/assets/a76f5770-9a03-42a5-9063-4aea62277209)

Thanks

**Comment by mikhail-vl** [comment]
@yosiasz As discussed, please look into using Data links.
