### ISSUE TITLE
Cannot install for grafana 10

### ISSUE THREAD

**Issue by asupawat** [VolkovLabs/business-table#41]
918383b4442b:/usr/share/grafana# grafana cli plugins install volkovlabs-table-panel
Error: ✗ 404: Plugin not found (Grafana v10.2.2 linux-amd64)

install under docker

**Comment by asupawat** [comment]
error also on mac os m2

aa608e9595a5:/usr/share/grafana# grafana cli plugins install volkovlabs-table-panel
Error: ✗ 404: Plugin not found (Grafana v10.2.2 linux-arm64)

**Comment by mikhail-vl** [comment]
@asupawat Panel is still under review by Grafana team as mentioned in the blog post: https://volkovlabs.io/blog/business-table-1.2.0/

  Grafana does not provide time estimation for the review. Meanwhile, you can download it from the GitHub and extract manually in the `plugins` folder.
