### ISSUE TITLE
Error when installing from Grafana Plugin Catalog

### ISSUE THREAD

**Issue by BrightGrafana** [VolkovLabs/business-table#44]
When installing the plugin on a Grafana Cloud instance from the Grafana Plugin Catalog, it fails with the error: "Error: The plugin volkovlabs-table-panel is not in a valid status: stub"

Grafana version: v11.3.0-75420

![grafana error](https://github.com/user-attachments/assets/8c722528-dbde-4f18-904c-0cda4510e516)

**Comment by mikhail-vl** [comment]
@BrightGrafana Thank you for your interest. The plugin is under review by Grafana team to include in the Grafana Catalog.

  Grafana does not provide time estimation for the review. Meanwhile, you can download it from the GitHub and extract manually in the `plugins` folder for local installation to try it out. For cloud it will be available only after review.
