### ISSUE TITLE
Text font, text font size and download csv issue.

### ISSUE THREAD

**Issue by marciop975** [VolkovLabs/business-table#48]
I really like the plugin, congratulations!

I would like to suggest adding the option to change the text font and font size, or perhaps just the font size.

This option exists in the older version of the Grafana table.

Another thing is the ability to download the CSV as it appears in the table. Currently, when I inspect, get data, and download, I always receive the full table instead of what's displayed in the table.

For example, I have a query with ITEM, MIN, and MAX. I created TAB1 with ITEM and MIN and TAB2 with ITEM and MAX. When I click TAB2, I see ITEM and MAX, but when I try to download it, I always get the complete table from the query with ITEM, MIN, and MAX.
  

    
![csv_download](https://github.com/user-attachments/assets/20b4d733-333f-484c-a733-46d0b6b25d2f)
![csv_download_MIN](https://github.com/user-attachments/assets/9f36ed74-9d81-4c4e-9d9c-4d2ae2ea3585)

**Comment by mikhail-vl** [comment]
@marciop975 We appreciate the feedback and feature requests.

  Updating font is similar to https://github.com/VolkovLabs/business-table/issues/22 which was opened for the header.
  We plan to address download https://github.com/VolkovLabs/business-table/issues/22 in the upcoming releases.
  Let us know if there is anything else.
