### ISSUE TITLE
Failed to add Data Links

### ISSUE THREAD

**Issue by huangsijun17** [VolkovLabs/business-table#49]
I add Data Links like the Grafana table, but it cannot be added.
Settings related to Data Links:
![image](https://github.com/user-attachments/assets/b9fd8e2f-038d-4f9b-9f4e-102983c5ac14)
Unexisting Data Links:
![image](https://github.com/user-attachments/assets/b65e4f3b-44b0-4011-9758-65d877ed150a)
Existing Data Links:
![image](https://github.com/user-attachments/assets/6bc3276f-31c4-4470-8158-010872ad7025)

**Comment by mikhail-vl** [comment]
Data links will be added in https://github.com/VolkovLabs/business-table/issues/45
