### ISSUE TITLE
Threshold color per column

### ISSUE THREAD

**Issue by 3Dnerd** [VolkovLabs/business-table#56]
I want to use business table to show columns with values and percentage of another column.
If percentage is negative I want to color the font (not the background) of the percentage column in red.
But only the percentage column not all columns. Is that possible? If not can it be implemented please?

Best would be if we can define a javascript function which returns the color value (based on calculation inside the function) to be more flexible compared to grafana's threshold system.

**Comment by asimonok** [comment]
@3Dnerd, if you want to have a colored column text based on threshold you should:
1. Set a cell type for the column to `Colored text`
<img width="713" alt="Screenshot 2024-09-17 at 10 45 04" src="https://github.com/user-attachments/assets/9c7827f4-10c0-4a4f-a5b7-c1b52b420945">

2. Set thresholds for the needed field in overrides based on your requirements
<img width="760" alt="Screenshot 2024-09-17 at 10 46 38" src="https://github.com/user-attachments/assets/f5606f8d-152b-40d5-bb94-71c43322c3cd">

3. Then, font color will be applied based on the thresholds only for the necessary column
<img width="1294" alt="Screenshot 2024-09-17 at 10 49 29" src="https://github.com/user-attachments/assets/c0d5cb67-f59d-432e-a91a-09e53b238fdd">

In addition, you can use transformations for percentage calculation.

Please let us know if there is anything else or the approach doesn't work for you
