### ISSUE TITLE
Allow to format footer

### ISSUE THREAD

**Issue by pabloveliz** [VolkovLabs/business-table#59]
Try a column with 2 values 3.1415295, then add a footer displaying the *Mean*. 
You'll see 3.14 in the value cells, but the footer has all the decimals, disregarding standard options / decimals setting.
![image](https://github.com/user-attachments/assets/622a1657-8b58-4654-bbca-2062f7b9eceb)

**Comment by asimonok** [comment]
@pabloveliz thank you for the opening the issue.
Footer formatting depends on the field settings. If you want to round decimals you should set decimals settings in standard options or in overrides for the needed field

Auto decimals
<img width="1311" alt="Screenshot 2024-09-17 at 10 34 57" src="https://github.com/user-attachments/assets/d9b3fde9-8294-455e-acb6-98e12c339bbb">

Decimals rounded
<img width="1321" alt="Screenshot 2024-09-17 at 10 35 11" src="https://github.com/user-attachments/assets/8f2a18a5-cd4f-438b-ae51-2bce8dc58d59">

Please let us know if there is anything else or if the approach doesn't work for you

**Comment by mikhail-vl** [comment]
@pabloveliz It may be the case as we are developing using 11.2.0. Could you please try and let us know.

**Comment by pabloveliz** [comment]
Made a test with grafana v10.2.3 from scratch (only input and table plugins) same bad result.

![10 2 3](https://github.com/user-attachments/assets/99775cf8-becb-4e22-bed7-8363a2fe1f6f)

Then made a test with v10.4.8 (latest) with same bad result.

![10 4 8](https://github.com/user-attachments/assets/97baf380-113d-4b5c-93d1-0d2e435e29ee)

Finally made a test with v11.2.0 and it works! So, I suppose this feature only works on v11.*.*

![11 2 0](https://github.com/user-attachments/assets/4aca889c-1210-49fb-bcf6-4e152f9b767c)

Thanks.

**Comment by mikhail-vl** [comment]
@pabloveliz Thank you for checking.

  Let us know if there is anything else.
