### ISSUE TITLE
Add support for the Data Links

### ISSUE THREAD

**Issue by nospaceandtime** [VolkovLabs/business-table#77]
We rely on Grafana Data links to navigate to other Grafana Dashboards. Having Data Links enabled in some form would make this Plugin even better. Thank you

![image](https://github.com/user-attachments/assets/db33cc1e-ab46-4dd0-82f0-b4481e9df067)

**Comment by mikhail-vl** [comment]
@nospaceandtime Data links support is coming in v1.3.0 later today.
