### ISSUE TITLE
The format set in the Unit is not applied in the aggregate row

### ISSUE THREAD

**Issue by rjk-tn** [VolkovLabs/business-table#83]
The format set in the Unit is not applied in the aggregate row
1 row --> aggregate row SUM -- wrong
2 row --> Total in Footer  -- right

![Schermata 2024-09-26 alle 19 27 13](https://github.com/user-attachments/assets/0fc27fbf-cf4c-46c1-84ac-da6cc4789c6f)

Thank's

**Comment by mikhail-vl** [comment]
@rjk-tn Thank you for reporting the issue. It's resolved in https://github.com/VolkovLabs/business-table/pull/79 and will be part of the upcoming release 1.4.0.
