### ISSUE TITLE
Using variable values within the column labels

### ISSUE THREAD

**Issue by cgravita** [VolkovLabs/business-table#97]
Good morning! 
First of all, I love this new table features. I have to work on it frequently and it was the last not very versatile element of grafana.

I would like to ask you to add the possibility of using the values ​​of the variables within the column labels. As you can see they are not loaded correctly.

![Screenshot From 2024-10-02 13-46-40](https://github.com/user-attachments/assets/76ea462e-ddad-41f0-94ad-637d88ea5cab)

**Comment by mikhail-vl** [comment]
@cgravita Thank you for the feature request. We will implement in the upcoming release.
