### ISSUE TITLE
Add a new row or delete a row

### ISSUE THREAD

**Issue by alpglide** [VolkovLabs/business-table#98]
how to add a new row or delete a row?

**Comment by mikhail-vl** [comment]
@alpglide Thank you for submitting feature request. Adding and deleting rows on our roadmap to implement in the future versions.

**Comment by Bruutal** [comment]
@alpglide 
While waiting for this feature to be released, I'm using this solution:

1.
I add an empty row in my query, with a dedicated field that tells if the line is a new one : 
`select
id,
my_field,
false as new_line

UNION

select
null as id,
null as my_field,
true as new_line`

2.
My request triggers an INSERT statement if new_line = true :
`DO $$
BEGIN
    IF ${payload.new_line:sqlstring} = 'true' THEN
        INSERT INTO my_table (my_field) 
        VALUES (${payload.my_field:sqlstring});
    ELSE
        UPDATE my_table
        SET my_field = ${payload.name:sqlstring}
        WHERE id = ${payload.id};
    END IF;
END $$;`

This way I display an empty line that serves as a placeholder for inserting a new line. That's not very elegant, off course, but it works just fine for now.
